[package]
name = "module"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
presenter = {path = "../presenter"}
reqwest = "0.10.6"
async-trait = "0.1.31"
serde_json = "1.0.53"