[package]
name = "presenter"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
rusoto_ce = "0.43.0"
slack-hook = "0.7"
